POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlY3RvciIsImlkIjoiNjZlMjIzYjM0MmZlNWU0OGQzZjk4MDNjIiwiaWF0IjoxNzI2MTA4MjM4fQ.-fscTJOH4MsVWnLH1BFdBiK13yg6jGiqRhGzxN1jb0U

{
    "title": "Blog title26",
    "author": "Blog author26",
    "url": "Blog aouthor26",
    "likes": 32
}